### ISSUE TITLE
How to add other tag?

### ISSUE THREAD

**Issue by breaker84** [reeset/ris_to_marc#3]
Dear Reese...

How do i add / map other ros code with marc?
Example AU = Main Author (100), AN = Record Num (001)

Regards

**Comment by reeset** [comment]
You will need to change the code.  But both of those values are currently defined.  You can find defined fields in the source file. https://github.com/reeset/ris_to_marc/blob/master/ris_to_marc/frmMain.cs

**Comment by breaker84** [comment]
And why when i convert it not include those tag?

**Comment by reeset** [comment]
No idea -- but if you look at the code, AU is defined as the 700 (because it's impossible to know if the AU is the main entry or not) and record number is placed outside of the 001 because again, this doesn't necessarily designate a control number in most systems.  But the plugin is designed to work on a very rigid version of ris -- if the format doesn't look like the expected specification, things could be missed I guess.

**Comment by breaker84** [comment]
Agreed...
I was thinking to create a RIS template for each system that i use...
So that i can assign that record number to 001..
But again the default one does not generate the tag..

Would you like to try it?

[Try.txt](https://github.com/reeset/ris_to_marc/files/2931210/Try.txt)
 Change .txt to .ris, Its from Proquest Dissertation
